// #72 icon-sprite generator.
//
// Vendors a curated slice of pixelarticons (MIT, halfmage/pixelarticons) into a
// single inline SVG sprite that BOTH rendering surfaces share (issue #72):
//   • the server-rendered askama chrome (crates/server/templates/shell.html,
//     which `{% include %}`s the sprite once), and
//   • the Svelte 5 islands (ui/src/lib/Icon.svelte emits `<use href="#icon-…">`).
// One source of truth, zero runtime fetches — the app is an offline desktop
// build, so nothing is loaded from a CDN.
//
// Source SVGs come from the locally-installed `pixelarticons` package
// (node_modules/pixelarticons/svg by default; override with PIXELARTICONS_SVG).
// Run `npm run build:icons` after `npm i` to (re)generate the committed sprite.
// The ICONS map below is the ONLY place a glyph→icon decision lives; add a row
// here to introduce a new icon, then reference `#icon-<id>` from either surface.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const svgDir = process.env.PIXELARTICONS_SVG ?? resolve(root, 'node_modules/pixelarticons/svg');
const outFile = resolve(root, '../crates/server/templates/_icons.svg');

// symbol id (`icon-<id>`) → pixelarticons file name (without .svg). The id is the
// stable name both surfaces reference; the file name is a pixelarticons detail.
const ICONS = {
  // Record / layout stepper (shell.html) + sidebar collapse toggle.
  first: 'arrow-bar-left',
  prev: 'chevron-left',
  next: 'chevron-right',
  last: 'arrow-bar-right',
  collapse: 'chevrons-horizontal',
  // Toolbar record actions (shell.html).
  delete: 'trash',
  find: 'search',
  // Layout-mode tool palette (RailTools.svelte).
  pointer: 'pointer',
  text: 'text-cursor',
  field: 'text-cursor-input',
  rect: 'square',
  ellipse: 'circle',
  // Inspector text-alignment segmented control (Inspector.svelte).
  'align-left': 'text-align-left',
  'align-center': 'text-align-center',
  'align-right': 'text-align-right',
  // Shared +/− glyphs: New / add-band / zoom-in reuse `plus`; the line tool and
  // zoom-out reuse `minus`. One symbol each, referenced from several controls.
  plus: 'plus',
  minus: 'minus',
};

// Pull the inner markup (the <path> elements) out of a pixelarticons file. Every
// source is a 24×24 `fill="currentColor"` icon, so the extracted paths inherit
// colour from the `<use>` site with no per-symbol fill.
function innerPaths(name) {
  const raw = readFileSync(resolve(svgDir, `${name}.svg`), 'utf8');
  const m = raw.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  if (!m) throw new Error(`unrecognised SVG shape in ${name}.svg`);
  return m[1].trim().replace(/\s+/g, ' ');
}

const license = readFileSync(resolve(root, 'vendor/pixelarticons/LICENSE'), 'utf8').trim();

const symbols = Object.entries(ICONS)
  .map(([id, name]) => `  <symbol id="icon-${id}" viewBox="0 0 24 24">${innerPaths(name)}</symbol>`)
  .join('\n');

// A hidden <svg> defs block: it renders nothing itself but registers every
// <symbol> for `<use>` elsewhere in the same document. `aria-hidden` + the
// `display:none` wrapper keep it out of the accessibility tree and layout.
const out = `{# GENERATED by ui/scripts/build-icons.mjs — do not edit by hand.
   Inline pixelarticons sprite (#72): a single source of truth referenced by both
   the askama chrome and the Svelte islands via <use href="#icon-…">. Icons are
   decorative; every control keeps its own title/aria-label.

   pixelarticons — MIT — https://github.com/halfmage/pixelarticons
   ${license.split('\n').join('\n   ')}
#}
<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">
${symbols}
</svg>
`;

writeFileSync(outFile, out);
console.log(`wrote ${outFile} (${Object.keys(ICONS).length} icons)`);
